<robot name="cam" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="cam_x" value="0.02" />
    <xacro:property name="cam_y" value="0.05" />
    <xacro:property name="cam_z" value="0.05" />
    <xacro:property name="cam_off_x" value="0.24" />
    <xacro:property name="cam_off_y" value="0" />
    <xacro:property name="cam_off_z" value="0.245" />

    <!-- <xacro:property name="cam_off_z" value="${base_length/2 + cam_z/2 }" /> -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="${cam_x} ${cam_y} ${cam_z}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
 
        <collision>
            <geometry>
                <box size="${cam_x} ${cam_y} ${cam_z}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:Box_inertial_matrix m="${0.01}" l="${cam_x}" w="${cam_y}" h="${cam_z}" />
 
    </link>
 
    <joint name="camera2base_link" type="fixed">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${cam_off_x} ${cam_off_y} ${cam_off_z}" />
    </joint>
    <gazebo reference="camera">
        <material>Gazebo/Blue</material>
    </gazebo>
 
</robot>