// Generated by gencpp from file msg_set/DroneState.msg
// DO NOT EDIT!


#ifndef MSG_SET_MESSAGE_DRONESTATE_H
#define MSG_SET_MESSAGE_DRONESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_set
{
template <class ContainerAllocator>
struct DroneState_
{
  typedef DroneState_<ContainerAllocator> Type;

  DroneState_()
    : drone_id(0)
    , grid_ids()
    , recent_attempt_time(0.0)
    , stamp(0.0)
    , pos()
    , vel()
    , yaw(0.0)
    , cur_state(0)  {
    }
  DroneState_(const ContainerAllocator& _alloc)
    : drone_id(0)
    , grid_ids(_alloc)
    , recent_attempt_time(0.0)
    , stamp(0.0)
    , pos(_alloc)
    , vel(_alloc)
    , yaw(0.0)
    , cur_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _drone_id_type;
  _drone_id_type drone_id;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _grid_ids_type;
  _grid_ids_type grid_ids;

   typedef double _recent_attempt_time_type;
  _recent_attempt_time_type recent_attempt_time;

   typedef double _stamp_type;
  _stamp_type stamp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _pos_type;
  _pos_type pos;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _vel_type;
  _vel_type vel;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef int32_t _cur_state_type;
  _cur_state_type cur_state;





  typedef boost::shared_ptr< ::msg_set::DroneState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_set::DroneState_<ContainerAllocator> const> ConstPtr;

}; // struct DroneState_

typedef ::msg_set::DroneState_<std::allocator<void> > DroneState;

typedef boost::shared_ptr< ::msg_set::DroneState > DroneStatePtr;
typedef boost::shared_ptr< ::msg_set::DroneState const> DroneStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_set::DroneState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_set::DroneState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_set::DroneState_<ContainerAllocator1> & lhs, const ::msg_set::DroneState_<ContainerAllocator2> & rhs)
{
  return lhs.drone_id == rhs.drone_id &&
    lhs.grid_ids == rhs.grid_ids &&
    lhs.recent_attempt_time == rhs.recent_attempt_time &&
    lhs.stamp == rhs.stamp &&
    lhs.pos == rhs.pos &&
    lhs.vel == rhs.vel &&
    lhs.yaw == rhs.yaw &&
    lhs.cur_state == rhs.cur_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_set::DroneState_<ContainerAllocator1> & lhs, const ::msg_set::DroneState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_set

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msg_set::DroneState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_set::DroneState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_set::DroneState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_set::DroneState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_set::DroneState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_set::DroneState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_set::DroneState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5585437c78c5e2a88978fc6a150fd46";
  }

  static const char* value(const ::msg_set::DroneState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5585437c78c5e2aULL;
  static const uint64_t static_value2 = 0x88978fc6a150fd46ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_set::DroneState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_set/DroneState";
  }

  static const char* value(const ::msg_set::DroneState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_set::DroneState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 drone_id\n"
"\n"
"int8[] grid_ids\n"
"float64 recent_attempt_time\n"
"float64 stamp\n"
"\n"
"# only used for simulation\n"
"float32[] pos\n"
"float32[] vel\n"
"float32 yaw\n"
"int32 cur_state\n"
;
  }

  static const char* value(const ::msg_set::DroneState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_set::DroneState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_id);
      stream.next(m.grid_ids);
      stream.next(m.recent_attempt_time);
      stream.next(m.stamp);
      stream.next(m.pos);
      stream.next(m.vel);
      stream.next(m.yaw);
      stream.next(m.cur_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_set::DroneState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_set::DroneState_<ContainerAllocator>& v)
  {
    s << indent << "drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "grid_ids[]" << std::endl;
    for (size_t i = 0; i < v.grid_ids.size(); ++i)
    {
      s << indent << "  grid_ids[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.grid_ids[i]);
    }
    s << indent << "recent_attempt_time: ";
    Printer<double>::stream(s, indent + "  ", v.recent_attempt_time);
    s << indent << "stamp: ";
    Printer<double>::stream(s, indent + "  ", v.stamp);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "vel[]" << std::endl;
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      s << indent << "  vel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vel[i]);
    }
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "cur_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cur_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_SET_MESSAGE_DRONESTATE_H
